### ISSUE TITLE
stable operator API

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#758]
Currently the operator is considered "alpha" (https://github.com/intel/pmem-csi/blob/devel/README.md#feature-status).

Before we can commit to maintaining a stable API, we need to:
- [x] revise the status (https://github.com/intel/pmem-csi/issues/611)
- [x] enable per-container resource specs (https://github.com/intel/pmem-csi/issues/616) and set reasonable defaults (https://github.com/intel/pmem-csi/issues/261)
- [x] revise certificate API (https://github.com/intel/pmem-csi/issues/759, https://github.com/intel/pmem-csi/issues/814)
- [x] finalize the operator installation procedure (https://github.com/intel/pmem-csi/issues/761)
- [x] test up- and downgrade scenarios

Once we are done, we need to change the channel in Operator Hub from alpha to beta.

**Comment by avalluri** [comment]
@pohly I think all the listed issues got addressed, Do you still have any in your mind before closing this and calling the operator API is stable?

**Comment by pohly** [comment]
Where do we have up- and downgrade tests?

What I meant with "test up- and downgrade scenarios", I meant installing one version of the operator, deploying a driver, and then updating resp. downgrading the operator.

**Comment by avalluri** [comment]
> Where do we have up- and downgrade tests?
I was mistaken, we have this for the driver but not the operator.

> What I meant with "test up- and downgrade scenarios", I meant installing one version of the operator, deploying a driver, and then updating resp. downgrading the operator.

Currently, we cannot support this as our `v1beta1` CRD API is _not_ backward compatible. Probably we should target this post 0.9 release, what do you think?

**Comment by pohly** [comment]
It feels too early to define a new API in 0.9.0 and immediately declare it "stable" without any outside feedback - that will prevent all future backwards incompatible changes or at least make them more difficult.

With that in mind I think we should move this issue to 1.0.

**Comment by avalluri** [comment]
Operator downgrade is not supported by the OLM hence we can't test that using OLM. Other than this all others listed in this issue are fixed.
